name: Build, Test and Release

on:
  push:
    tags:
      - "v*" # Trigger on version tags (e.g., v1.0.0)
  pull_request:
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run unit tests
        run: |
          go test -tags=unit ./...
